---
_firefox_policy_dir: /usr/lib/firefox-esr/distribution
_firefox_package: firefox-esr

_base_packages:
  - git
  - stow
  - curl
  - wget
  - jq
  - ripgrep
  - fd-find
  - fzf
  - bat
  - tmux
  - neovim
  - zsh
  - foot
  - mpv
  - zathura
  - python3-pip
  - pipx
  - flatpak
  - ufw
  - openvpn
  - wireguard-tools
  - unzip
  - tar
  - gcc
  - make
  - shellcheck
  - firefox-esr
  - pass
  - gnupg
  - pinentry-curses
