---
_firefox_policy_dir: /usr/lib64/firefox/distribution
_firefox_package: firefox

_base_packages:
  - git
  - stow
  - curl
  - wget
  - jq
  - ripgrep
  - fd-find
  - fzf
  - bat
  - tmux
  - neovim
  - zsh
  - foot
  - mpv
  - zathura
  - python3-pip
  - pipx
  - podman
  - firewalld
  - wl-clipboard
  - openvpn
  - wireguard-tools
  - unzip
  - tar
  - gcc
  - make
  - ShellCheck
  - flatpak
  - firefox
  - pass
  - gnupg
  - pinentry
