---
all:
  children:
    fedora_workstation:
      hosts:
        fedora43-utm:
          ansible_host: 192.168.64.6
          ansible_user: michael
          ansible_shell_executable: /bin/sh
          ansible_become: true
    hyprland:
      hosts:
        fedora43-utm:
    pentest_core:
      hosts:
        fedora43-utm:
    vpn_clients:
      hosts:
        fedora43-utm:
